//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramwork5API
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery
    {
        public delivery()
        {
            this.deliveryparts = new HashSet<deliverypart>();
        }
    
        public int iddeliveryId { get; set; }
        public string deliverycol { get; set; }
        public Nullable<System.DateTime> deliveryDate { get; set; }
        public System.DateTime deliveryDate2 { get; set; }
        public string deliverycol1 { get; set; }
        public string deliverycol2 { get; set; }
        public string deliverycol3 { get; set; }
    
        public virtual ICollection<deliverypart> deliveryparts { get; set; }
    }
}
