//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramwork5API
{
    using System;
    using System.Collections.Generic;
    
    public partial class deliverypart
    {
        public int id { get; set; }
        public Nullable<int> iddeliveryId { get; set; }
        public string deliverypartName { get; set; }
    
        public virtual delivery delivery { get; set; }
    }
}
